"use client";

import {
  Accessibility,
  Activity,
  Award,
  BadgeCheck,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FlaskConical,
  Gift,
  GraduationCap,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  Languages,
  LineChart,
  MapPin,
  Medal,
  Microscope,
  Moon,
  Scale,
  ScanLine,
  ShieldCheck,
  Stethoscope,
  Syringe,
  Users,
  Video,
  Wind,
  type LucideIcon,
} from "lucide-react";
import type { LucideIconKey } from "./icon-keys";

export const LUCIDE_ICONS: Record<LucideIconKey, LucideIcon> = {
  accessibility: Accessibility,
  activity: Activity,
  award: Award,
  "badge-check": BadgeCheck,
  brain: Brain,
  briefcase: Briefcase,
  "building-2": Building2,
  calendar: Calendar,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "flask-conical": FlaskConical,
  gift: Gift,
  "graduation-cap": GraduationCap,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  hospital: Hospital,
  languages: Languages,
  "line-chart": LineChart,
  "map-pin": MapPin,
  medal: Medal,
  microscope: Microscope,
  moon: Moon,
  scale: Scale,
  "scan-line": ScanLine,
  "shield-check": ShieldCheck,
  stethoscope: Stethoscope,
  syringe: Syringe,
  users: Users,
  video: Video,
  wind: Wind,
};

export function getLucideIcon(key: LucideIconKey): LucideIcon {
  return LUCIDE_ICONS[key];
}
